baseURL = '/'
languageCode = 'en-us'
title = 'Chloe Jo'
theme = "cactus"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = 'Bookshelf'
url = "/bookshelves"
weight = 3

[[menu.main]]
name = "Evergreen"
url = "/evergreen"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params] 
	googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # description = ""
  # The discription is not very convenient if I want to incorporae link... 
  
  mainSection = "posts"

	tagsOverview = true

  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

	# Mathsjax syntax
	mathjax = true
	
	# the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ChloeZhou1997"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/qiaohui-zhou-9082b099/"
  [[params.social]]
    name = "email"
    link = "qz111@georgetown.edu"  # no need for "mailto:" in the head
  [[params.bookshelf]]
    name = "goodreads"
    link = "https://www.goodreads.com/user/show/24168276-chloe-zhou"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  status = 'status'
  bookCate = 'bookCate'